---
# Staging Environment Inventory
# =====================================

all:
  vars:
    deploy_env: staging
    env_short: stg
    ansible_user: addheputra
    ansible_ssh_private_key_file: /home/addheputra/.ssh/shannon-gcp
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root

  children:
    localhost:
      hosts:
        127.0.0.1:
          ansible_connection: local

    staging:
      hosts:
        ocl-openclaw-stg-20260305011114-509:
          ansible_host: 35.219.42.250