---
- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Reload sysctl
  command: sysctl -p /etc/sysctl.conf